// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDsTx_CsZtHx559ChLS8RbGo8GWi4uJ16A',
    appId: '1:295599090816:web:35d8f00317555b98cb8a65',
    messagingSenderId: '295599090816',
    projectId: 'backendgolang',
    authDomain: 'backendgolang.firebaseapp.com',
    storageBucket: 'backendgolang.firebasestorage.app',
    measurementId: 'G-X7TY3SSJ2T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAw2fr7HZI3bneIhNX1UdvSiUdXKhKbFxA',
    appId: '1:295599090816:android:3e66223914f67204cb8a65',
    messagingSenderId: '295599090816',
    projectId: 'backendgolang',
    storageBucket: 'backendgolang.firebasestorage.app',
  );
}
